//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceClient.LHWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cnblogs.com/zhili/", ConfigurationName="LHWebService.LearningHardWebServiceSoap")]
    public interface LearningHardWebServiceSoap {
        
        // CODEGEN: 消息 HelloLearningHardRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cnblogs.com/zhili/HelloLearningHard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceClient.LHWebService.HelloLearningHardResponse HelloLearningHard(WebServiceClient.LHWebService.HelloLearningHardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cnblogs.com/zhili/HelloLearningHard", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceClient.LHWebService.HelloLearningHardResponse> HelloLearningHardAsync(WebServiceClient.LHWebService.HelloLearningHardRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cnblogs.com/zhili/")]
    public partial class MySoapHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloLearningHard", WrapperNamespace="http://www.cnblogs.com/zhili/", IsWrapped=true)]
    public partial class HelloLearningHardRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cnblogs.com/zhili/")]
        public WebServiceClient.LHWebService.MySoapHeader MySoapHeader;
        
        public HelloLearningHardRequest() {
        }
        
        public HelloLearningHardRequest(WebServiceClient.LHWebService.MySoapHeader MySoapHeader) {
            this.MySoapHeader = MySoapHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloLearningHardResponse", WrapperNamespace="http://www.cnblogs.com/zhili/", IsWrapped=true)]
    public partial class HelloLearningHardResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cnblogs.com/zhili/")]
        public WebServiceClient.LHWebService.MySoapHeader MySoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cnblogs.com/zhili/", Order=0)]
        public string HelloLearningHardResult;
        
        public HelloLearningHardResponse() {
        }
        
        public HelloLearningHardResponse(WebServiceClient.LHWebService.MySoapHeader MySoapHeader, string HelloLearningHardResult) {
            this.MySoapHeader = MySoapHeader;
            this.HelloLearningHardResult = HelloLearningHardResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LearningHardWebServiceSoapChannel : WebServiceClient.LHWebService.LearningHardWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LearningHardWebServiceSoapClient : System.ServiceModel.ClientBase<WebServiceClient.LHWebService.LearningHardWebServiceSoap>, WebServiceClient.LHWebService.LearningHardWebServiceSoap {
        
        public LearningHardWebServiceSoapClient() {
        }
        
        public LearningHardWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LearningHardWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LearningHardWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LearningHardWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceClient.LHWebService.HelloLearningHardResponse WebServiceClient.LHWebService.LearningHardWebServiceSoap.HelloLearningHard(WebServiceClient.LHWebService.HelloLearningHardRequest request) {
            return base.Channel.HelloLearningHard(request);
        }
        
        public string HelloLearningHard(ref WebServiceClient.LHWebService.MySoapHeader MySoapHeader) {
            WebServiceClient.LHWebService.HelloLearningHardRequest inValue = new WebServiceClient.LHWebService.HelloLearningHardRequest();
            inValue.MySoapHeader = MySoapHeader;
            WebServiceClient.LHWebService.HelloLearningHardResponse retVal = ((WebServiceClient.LHWebService.LearningHardWebServiceSoap)(this)).HelloLearningHard(inValue);
            MySoapHeader = retVal.MySoapHeader;
            return retVal.HelloLearningHardResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceClient.LHWebService.HelloLearningHardResponse> WebServiceClient.LHWebService.LearningHardWebServiceSoap.HelloLearningHardAsync(WebServiceClient.LHWebService.HelloLearningHardRequest request) {
            return base.Channel.HelloLearningHardAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceClient.LHWebService.HelloLearningHardResponse> HelloLearningHardAsync(WebServiceClient.LHWebService.MySoapHeader MySoapHeader) {
            WebServiceClient.LHWebService.HelloLearningHardRequest inValue = new WebServiceClient.LHWebService.HelloLearningHardRequest();
            inValue.MySoapHeader = MySoapHeader;
            return ((WebServiceClient.LHWebService.LearningHardWebServiceSoap)(this)).HelloLearningHardAsync(inValue);
        }
    }
}
