//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.6421
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Demo.Service
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "WCF.Demo.Service", ConfigurationName = "IAdd")]
    public interface IAdd
    {

        [System.ServiceModel.OperationContractAttribute(Action = "WCF.Demo.Service/IAdd/DoWork", ReplyAction = "WCF.Demo.Service/IAdd/DoWorkResponse")]
        bool DoWork(WCF.Demo.Model.User user);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IAddChannel : IAdd, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AddClient : System.ServiceModel.ClientBase<IAdd>, IAdd
    {

        public AddClient()
        {
        }

        public AddClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public AddClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public AddClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public AddClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public bool DoWork(WCF.Demo.Model.User user)
        {
            return base.Channel.DoWork(user);
        }
    }
}
